### ISSUE TITLE
it does not work.

### ISSUE THREAD

**Issue by josepchaques** [philroche/finisherpixdownloader#1]
Hi!

I can't make it work, have they updated the website and do I have to update script?

thank you!

**Comment by philroche** [comment]
I haven't used the site in a long time. What race and what bib number are you trying to download?

**Comment by josepchaques** [comment]
Hi,

Cascais Ironman 2021 and my pib is 677. The url is:
https://www.finisherpix.com/es/photos/4148/677

could you help me? I would also like to know how you have done it? :)

Regards!

Josep

**Comment by philroche** [comment]
Hi Josep,

They had indeed changed the website. I have updated the script now @ https://github.com/philroche/finisherpixdownloader/commit/e1d4fcadbc73dcdd6522e0fbc3e9cd9fd20f72d2

And your photos are available @ 

https://finisherpixdownloader.tinyviking.ie/download/?filepath=web/downloads/4148/677.zip

You can also use https://finisherpixdownloader.tinyviking.ie/ now too.

Congrats on the race!!
